### ISSUE TITLE
Python 3.14.0a6: ImportError: cannot import name '_ERR_MSG' from 'importlib._bootstrap'

### ISSUE THREAD

**Issue by hroncok** [encukou/zombie-imp#4]
zombie-imp fails to import with Python 3.14.0a6:

```
ImportError: Failed to import test module: test_zombie_imp
Traceback (most recent call last):
  File "/usr/lib64/python3.14/unittest/loader.py", line 426, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.14/unittest/loader.py", line 367, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/builddir/build/BUILD/python-zombie-imp-0.0.2-build/zombie-imp-0.0.2/test_zombie_imp/test_zombie_imp.py", line 25, in <module>
    import zombie_imp as imp  #!! this should be the only difference between test_imp and test_zombie_imp
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/python-zombie-imp-0.0.2-build/zombie-imp-0.0.2/zombie_imp/__init__.py", line 1, in <module>
    from .imp_3_11 import *
  File "/builddir/build/BUILD/python-zombie-imp-0.0.2-build/zombie-imp-0.0.2/zombie_imp/imp_3_11.py", line 23, in <module>
    from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_name
ImportError: cannot import name '_ERR_MSG' from 'importlib._bootstrap' (/usr/lib64/python3.14/importlib/_bootstrap.py)
```

Caused by https://github.com/python/cpython/commit/857bdba0ac66ed7963e9fca45ab1a5f7a32b4bfb

Used only in https://github.com/encukou/zombie-imp/blob/main/zombie_imp/imp_3_11.py#L300

Original definition of `_ERR_MSG`: `_ERR_MSG = _ERR_MSG_PREFIX + '{!r}'`
